server:
    port: 8086
    servlet:
        context-path: /helloboot

spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/catering?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root

    slaver:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.10.242:1521:orcl
      username: emerp
      password: e97896

## 该配置节点为独立的节点，将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#    mapper-locations:  classpath*:com/hugmount/*/mapper/*.xml  # 注意：一定要对应mapper映射xml文件的所在路径
#    type-aliases-package: com.hugmount.helloboot.*.pojo # 注意：对应实体类的路径

## 配置pageHelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

## 多数据源配置
db_oracle: # 数据源2
    datasource:
#        driver-class-name: oracle.jdbc.OracleDriver
        jdbcUrl: jdbc:oracle:thin:@192.168.10.242:1521:orcl
        username: emerp
        password: e97896
#        type: com.alibaba.druid.pool.DruidDataSource
#        masterMapperLocations: classpath*:com/hugmount/*/product/mapper/*.xml

db_mysql:
    datasource:
#        driver-Class-Name: com.mysql.cj.jdbc.Driver
        # 使用mysql的jdbc驱动最新版（6.0+）时加上 serverTimezone=UTC
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/catering?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: root