#在Spring Boot中多环境配置文件名需要满足application-{profile}.properties的格式，
#其中{profile}对应你的环境标识，比如：
#application-dev.properties：开发环境
#application-test.properties：测试环境
#application-prod.properties：生产环境

# 切换配置文件, pro 为错误配置,应该无法启动
spring:
  profiles:
    active: dev